# Generated by Django 5.1.15 on 2026-06-20 02:17

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("retirement", "Retirement"),
                            ("education", "Education"),
                            ("house", "House Purchase"),
                            ("emergency_fund", "Emergency Fund"),
                            ("vacation", "Vacation"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "monthly_contribution",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("target_date", models.DateField()),
                (
                    "expected_return",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.07"), max_digits=6
                    ),
                ),
                (
                    "inflation_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.03"), max_digits=5
                    ),
                ),
                ("is_achieved", models.BooleanField(default=False)),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_financial_goals",
                "ordering": ["priority", "target_date"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "cash_balance",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("target_allocation", models.JSONField(blank=True, default=dict)),
                ("benchmark_ticker", models.CharField(default="SPY", max_length=20)),
                (
                    "annualized_return",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "last_performance_update",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_portfolios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticker", models.CharField(blank=True, max_length=20)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("dividend", "Dividend"),
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("split", "Stock Split"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cost_basis",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "realized_gain",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "holding_period_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_long_term", models.BooleanField(blank=True, null=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_transactions",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("equity", "Equity"),
                            ("fixed_income", "Fixed Income"),
                            ("real_estate", "Real Estate"),
                            ("commodity", "Commodity"),
                            ("crypto", "Crypto"),
                            ("cash", "Cash"),
                            ("alternative", "Alternative"),
                        ],
                        default="equity",
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("average_cost", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "unrealized_pnl_pct",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "day_change",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "day_change_pct",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=8
                    ),
                ),
                ("price_updated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_holdings",
                "ordering": ["-market_value"],
                "unique_together": {("portfolio", "ticker")},
            },
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("cash_balance", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "holdings_value",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "daily_return_pct",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("holdings_snapshot", models.JSONField(default=dict)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_snapshots",
                "ordering": ["-date"],
                "unique_together": {("portfolio", "date")},
            },
        ),
    ]
