# Generated by Django 5.1.15 on 2026-06-20 02:17

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("country", models.CharField(default="US", max_length=2)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_token", models.UUIDField(blank=True, null=True)),
                ("password_reset_token", models.UUIDField(blank=True, null=True)),
                ("password_reset_expires", models.DateTimeField(blank=True, null=True)),
                (
                    "risk_profile",
                    models.CharField(
                        choices=[
                            ("conservative", "Conservative"),
                            ("moderate_conservative", "Moderate Conservative"),
                            ("moderate", "Moderate"),
                            ("moderate_aggressive", "Moderate Aggressive"),
                            ("aggressive", "Aggressive"),
                        ],
                        default="moderate",
                        max_length=30,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(default=50, help_text="0-100"),
                ),
                (
                    "annual_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "net_worth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "investment_horizon_years",
                    models.PositiveSmallIntegerField(default=10),
                ),
                (
                    "tax_bracket_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("22.00"),
                        help_text="Marginal tax rate in percent",
                        max_digits=5,
                    ),
                ),
                ("notify_price_alerts", models.BooleanField(default=True)),
                ("notify_rebalance", models.BooleanField(default=True)),
                ("notify_weekly_digest", models.BooleanField(default=True)),
                ("notify_tax_opportunities", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "accounts_users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("price_alert", "Price Alert"),
                            ("rebalance", "Rebalance Required"),
                            ("tax_harvest", "Tax Harvest Opportunity"),
                            ("goal_milestone", "Goal Milestone"),
                            ("system", "System"),
                            ("weekly_digest", "Weekly Digest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("above", "Price Above"),
                            ("below", "Price Below"),
                            ("change_pct", "% Change"),
                        ],
                        max_length=10,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=4, max_digits=18)),
                ("is_active", models.BooleanField(default=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_price_alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
