# Generated by Django 5.1.15 on 2026-06-20 02:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketQuoteCache",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "previous_close",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "change",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "change_pct",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("volume", models.BigIntegerField(null=True)),
                ("market_cap", models.BigIntegerField(null=True)),
                (
                    "week_52_high",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "week_52_low",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "pe_ratio",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(decimal_places=4, max_digits=8, null=True),
                ),
                (
                    "beta",
                    models.DecimalField(decimal_places=4, max_digits=8, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "market_quote_cache",
            },
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="My Watchlist", max_length=100)),
                ("tickers", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "market_watchlists",
                "ordering": ["-created_at"],
            },
        ),
    ]
